name: "🚀 Fix Report"
description: "버그 수정 사항을 기록하는 템플릿"
title: "fix: "
body:
  - type: input
    attributes:
      label: 🔗 관련 이슈
      description: "해당 버그와 연결된 이슈 번호를 입력해주세요. (예: #123)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🐛 버그 현상
      description: 발생한 버그의 증상과 상황을 설명해주세요.
      placeholder: |
        - 예: 로그인 버튼이 반응하지 않음
        - 특정 브라우저에서 스타일 깨짐
        - 콘솔에 오류 메시지 출력됨
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🛠 수정 방향
      description: 현재까지 파악한 버그의 원인이나 버그를 어떻게 해결할 계획인지 간단히 설명해주세요.
      placeholder: |
        - DOM 렌더링 순서 문제일 가능성 있음
        - useEffect 의존성 배열 수정 예정
        - 조건문에 null 체크 추가
        - CSS 우선순위 조정
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업 내역
      description: 계획 중인 작업을 체크리스트로 정리해주세요.
      placeholder: |
        <ex. 예시 지문>
        - [ ] <체크 1>
        - [ ] <체크 2>
      value: |
        - [ ] <#이슈 1> <작업 내용>
        - [ ] <#이슈 1> <작업 내용>
        - [ ] <#이슈 1> <작업 내용>
        - [ ] 더입력 ...
      render: ''
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 리뷰 요구사항 (선택)
      description: 코드 리뷰 요청이 필요한 부분을 작성해주세요.
      placeholder: |
        - 기존 코드와 비교해서 변경된 부분의 논리적 타당성을 봐주세요.
        - 리팩토링할 수 있는 여지가 있는지 피드백 부탁드립니다.
        - 테스트 커버리지가 충분한지 확인해 주세요.
    validations:
      required: false